# Site settings
title: Mathifold
email: mathifold@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web para aprender matemáticas
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mathifold.org" # the base hostname & protocol for your site
github_username: mathifold

# Build settings
markdown: kramdown

exclude: ['node_modules', '_pages', 'README.md','_publish.sh','app.yaml', '_docs']
#include: ['_pages']

kramdown:
  math_engine_opts:
    preview: true

permalink: /:categories/:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: post
      type: posts
  -
    scope:
      path: en
    values:
      lang: en
  -
    scope:
      path: es
    values:
      lang: es
  -
    scope:
      path: _posts/en
    values:
      lang: en
  -
    scope:
      path: _posts/es
    values:
      lang: es
