application: high-acre-87013
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\..*)$
  static_files: _site/\1
  upload: _site/.*$
- url: /([^\.]*)$
  static_files: _site/\1/index.html
  upload: _site/.*$

